# Generated by Django 4.1.7 on 2023-07-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=50)),
                ('fecha_inscripcion', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO ASISTEN', 'No asisten')], max_length=20)),
                ('hora_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
